import { isSameDay } from 'date-fns';
import type { Drill } from '../types';

export type DrillCategory = Drill['category'];

export type DrillCompletion = {
  drill_id: string;
  completed_at: string;
};

export const DRILL_CATEGORY_LABELS: Record<DrillCategory, string> = {
  putting: 'Putting',
  short_game: 'Petit jeu',
  approach: 'Approches',
  driving: 'Mise en jeu',
  mental: 'Mental',
};

export const DRILL_DIFFICULTY_LABELS: Record<Drill['difficulty'], string> = {
  beginner: 'Débutant',
  intermediate: 'Intermédiaire',
  advanced: 'Avancé',
};

export const DRILLS: Drill[] = [
  {
    id: '1',
    title: 'Gate Drill',
    description: 'Place deux tees à la largeur de ton putter à 50cm du trou. Rentre 10 putts de suite sans toucher les tees.',
    youtube_url: 'https://www.youtube.com/watch?v=k9nN-FTM6eA',
    category: 'putting',
    difficulty: 'beginner',
    duration_minutes: 10,
    attempts: 10,
    success_threshold: 10,
    success_rule: 'Rentrer 10 putts de suite depuis 50 cm sans toucher les tees',
    steps: [
      'Place ta balle à 50 cm du trou, sur un putt droit.',
      'Plante deux tees de part et d’autre de la tête de ton putter, à peine plus écartés qu’elle.',
      'Fais passer ton putter entre les tees à l’aller comme au retour.',
      'Compte tes putts rentrés d’affilée ; au premier tee touché, repars à zéro.',
    ],
    equipment: ['Putter', '1 balle', '2 tees'],
  },
  {
    id: '2',
    title: 'Clock Drill — distance',
    description: 'Place 4 balles à 1m, 2m, 3m et 4m du trou (comme une horloge). Fais le tour complet sans 3-putter.',
    youtube_url: null,
    category: 'putting',
    difficulty: 'intermediate',
    duration_minutes: 15,
    attempts: 4,
    success_threshold: 4,
    success_rule: 'Terminer les 4 distances sans 3-putt',
    steps: [
      'Place 4 balles en ligne droite, à 1, 2, 3 et 4 m du trou.',
      'Joue chaque balle à son tour, de la plus proche à la plus éloignée.',
      'Compte une distance réussie quand la balle est rentrée en deux putts ou moins.',
      'Au premier 3-putt, recommence le tour depuis la première balle.',
    ],
    equipment: ['Putter', '4 balles'],
  },
  {
    id: '3',
    title: '100 putts de 1 mètre',
    description: 'Rentre 100 putts de 1 mètre consécutifs. Si tu rates, recommence depuis 0. Construit la confiance.',
    youtube_url: null,
    category: 'putting',
    difficulty: 'beginner',
    duration_minutes: 20,
    attempts: 100,
    success_threshold: 100,
    success_rule: 'Rentrer 100 putts de 1 m d’affilée, en repartant de zéro à chaque raté',
    steps: [
      'Choisis un putt droit de 1 m et marque ta position avec un tee.',
      'Putte et compte à voix haute chaque balle rentrée.',
      'Au premier raté, reviens à zéro sans te décourager.',
      'Arrête-toi à 100 ou au bout de tes 20 minutes, et note ta meilleure série.',
    ],
    equipment: ['Putter', '1 à 3 balles', 'Tee ou marqueur'],
  },
  {
    id: '16',
    title: 'Putts de 1,5 mètre',
    description: 'Le putt à rentrer pour sauver le par. Dix balles depuis une seule distance, avec la même routine à chaque fois.',
    youtube_url: null,
    category: 'putting',
    difficulty: 'beginner',
    duration_minutes: 10,
    attempts: 10,
    success_threshold: 6,
    success_rule: 'Réussir 6 putts sur 10 depuis 1,5 m',
    steps: [
      'Choisis un putt presque plat et marque ton point de départ à 1,5 m du trou.',
      'Joue tes 10 balles depuis ce point, avec la même routine à chaque putt.',
      'Reste immobile jusqu’à ce que la balle soit partie.',
      'Compte les putts rentrés et note ton score sur 10.',
    ],
    equipment: ['Putter', '10 balles', 'Tee ou marqueur'],
  },
  {
    id: '17',
    title: 'Porte de 3 mètres',
    description: 'Une porte juste devant la balle t’oblige à partir sur la bonne ligne. Tu juges ensuite ta vitesse jusqu’au trou.',
    youtube_url: null,
    category: 'putting',
    difficulty: 'intermediate',
    duration_minutes: 15,
    attempts: 10,
    success_threshold: 6,
    success_rule: 'Réussir 6 putts sur 10 depuis 3 m : balle passée dans la porte, rentrée ou arrêtée à moins de 60 cm du trou',
    steps: [
      'Marque un point de départ à 3 m du trou, sur un putt droit ou presque.',
      'Plante deux tees à 1 m devant la balle, juste plus écartés que sa largeur.',
      'Putte : la balle doit traverser la porte sans toucher les tees.',
      'Compte le putt réussi s’il est rentré ou arrêté à moins de 60 cm du trou.',
    ],
    equipment: ['Putter', '10 balles', '2 tees'],
  },
  {
    id: '18',
    title: 'Cercle de 1 mètre',
    description: 'Quatre points autour du trou t’obligent à lire des pentes différentes sur un putt très court.',
    youtube_url: null,
    category: 'putting',
    difficulty: 'intermediate',
    duration_minutes: 10,
    attempts: 20,
    success_threshold: 18,
    success_rule: 'Réussir 18 putts sur 20 depuis 1 m, répartis autour du trou',
    steps: [
      'Place 4 balles autour du trou, à 1 m, comme les quatre points d’une boussole.',
      'Joue les quatre balles une à une, en relisant la pente à chaque point.',
      'Ramasse tes balles et recommence jusqu’à 5 tours, soit 20 putts.',
      'Compte les putts rentrés et vise 18 sur 20.',
    ],
    equipment: ['Putter', '4 balles'],
  },
  {
    id: '19',
    title: 'Lag putt à 10 mètres',
    description: 'Sur un long putt, la vitesse compte plus que la ligne. Le but est de laisser la balle assez près pour finir en deux putts.',
    youtube_url: null,
    category: 'putting',
    difficulty: 'intermediate',
    duration_minutes: 12,
    attempts: 10,
    success_threshold: 8,
    success_rule: 'Réussir 8 putts sur 10 depuis 10 m, balle arrêtée à moins de 1,5 m du trou',
    steps: [
      'Choisis un putt d’environ 10 m sur le green d’entraînement.',
      'Pose quatre tees autour du trou, à 1,5 m, pour repérer la zone d’arrivée.',
      'Regarde le trou et fais un swing d’essai de la longueur qui correspond à la distance.',
      'Joue 10 balles et compte celles arrêtées dans la zone, devant ou derrière le trou.',
    ],
    equipment: ['Putter', '10 balles', '4 tees'],
  },
  {
    id: '20',
    title: 'Parcours de 9 putts',
    description: 'Neuf trous de putting, deux putts au maximum par trou. Tu travailles la vitesse et la lecture comme pendant un vrai round.',
    youtube_url: null,
    category: 'putting',
    difficulty: 'intermediate',
    duration_minutes: 20,
    attempts: 9,
    success_threshold: 7,
    success_rule: 'Réussir 7 trous sur 9 en deux putts maximum',
    steps: [
      'Choisis 9 départs à des distances variées, de 2 à 12 m, vers différents trous du green.',
      'Joue chaque trou avec une seule balle, sans seconde chance.',
      'Compte un trou réussi quand la balle est rentrée en deux putts ou moins.',
      'Note ton total de putts et vise 7 trous réussis sur 9.',
    ],
    equipment: ['Putter', '1 balle', 'Carnet ou téléphone'],
  },
  {
    id: '21',
    title: 'Putts en dévers',
    description: 'Sur un putt qui tourne, tu dois choisir un point de visée et une vitesse. Ce drill t’apprend à décider avant de jouer.',
    youtube_url: null,
    category: 'putting',
    difficulty: 'advanced',
    duration_minutes: 15,
    attempts: 10,
    success_threshold: 4,
    success_rule: 'Réussir 4 putts sur 10 depuis 2 m, sur une pente latérale',
    steps: [
      'Trouve un putt de 2 m avec une pente nette de la gauche vers la droite, ou l’inverse.',
      'Repère le point de la courbe où la balle doit passer et vise-le plutôt que le trou.',
      'Joue 5 balles, puis change de côté et joue 5 balles sur la pente opposée.',
      'Compte les putts rentrés et vise 4 sur 10.',
    ],
    equipment: ['Putter', '10 balles', 'Tee ou marqueur'],
  },
  {
    id: '22',
    title: 'Putts sur la serviette',
    description: 'Une serviette derrière le trou fixe la bonne vitesse : assez de force pour atteindre le trou, jamais plus de 50 cm au-delà.',
    youtube_url: null,
    category: 'putting',
    difficulty: 'beginner',
    duration_minutes: 10,
    attempts: 10,
    success_threshold: 6,
    success_rule: 'Réussir 6 putts sur 10 depuis 4 m : balle rentrée ou arrêtée sur la serviette',
    steps: [
      'Pose une serviette pliée juste derrière le trou, sur 50 cm de profondeur.',
      'Marque un départ à 4 m du trou, sur un putt plat.',
      'Joue 10 balles avec juste assez de vitesse pour finir sur la serviette si elles ne tombent pas.',
      'Compte les balles rentrées ou arrêtées sur la serviette ; une balle trop courte ou qui la dépasse ne compte pas.',
    ],
    equipment: ['Putter', '10 balles', 'Serviette'],
  },
  {
    id: '4',
    title: 'Chip & Run 50/50',
    description: "Depuis le rough, chipe vers une cible à 10m. L'objectif est que la balle roule autant qu'elle vole.",
    youtube_url: 'https://www.youtube.com/watch?v=dTy2Aqf5ZCY',
    category: 'short_game',
    difficulty: 'beginner',
    duration_minutes: 20,
    attempts: 10,
    success_threshold: 6,
    success_rule: 'Arrêter 6 balles sur 10 à moins de 2 m de la cible',
    steps: [
      'Pose une cible à 10 m (serviette ou tee) et place tes balles dans l’herbe haute.',
      'Prends un fer 8 ou 9, les mains en avant de la balle et le poids sur le pied avant.',
      'Fais un petit swing sans casser les poignets : la balle doit rouler autant qu’elle vole.',
      'Joue 10 balles et compte celles arrêtées à moins de 2 m de la cible.',
    ],
    equipment: ['Fer 8 ou 9', '10 balles', 'Serviette'],
  },
  {
    id: '5',
    title: 'Sortie de bunker ciblée',
    description: "Trace un cercle de 1m autour du trou. Sors 10 balles de bunker. Objectif: 7/10 dans le cercle.",
    youtube_url: 'https://www.youtube.com/watch?v=eCPndwLPSug',
    category: 'short_game',
    difficulty: 'intermediate',
    duration_minutes: 20,
    attempts: 10,
    success_threshold: 7,
    success_rule: 'Sortir 7 balles sur 10 dans le cercle de 1 m autour du trou',
    steps: [
      'Trace un cercle de 1 m autour du trou avec des tees ou une corde.',
      'Ouvre légèrement la face de ton sand wedge et enfonce tes pieds dans le sable.',
      'Fais entrer le club dans le sable 5 cm derrière la balle, sans chercher à la toucher.',
      'Joue 10 balles et compte celles qui finissent dans le cercle.',
      'Ratisse le bunker avant de partir.',
    ],
    equipment: ['Sand wedge', '10 balles', 'Râteau'],
  },
  {
    id: '6',
    title: 'Up & Down challenge',
    description: "50m du green, 10 essais. Compte tes up & downs réussis. Objectif: 5/10 minimum.",
    youtube_url: null,
    category: 'short_game',
    difficulty: 'intermediate',
    duration_minutes: 25,
    attempts: 10,
    success_threshold: 5,
    success_rule: 'Réussir 5 up & downs sur 10 : balle sur le green puis rentrée en un putt',
    steps: [
      'Choisis une position à environ 50 m du green, le drapeau bien visible.',
      'Joue un pitch pour poser la balle sur le green.',
      'Joue ensuite la balle jusqu’au trou au putter, sans seconde chance.',
      'Compte un up & down quand le trou est fini en deux coups depuis ta position.',
      'Répète 10 fois en changeant de position.',
    ],
    equipment: ['Wedges', 'Putter', '10 balles'],
  },
  {
    id: '23',
    title: 'Chip sur la serviette',
    description: 'Choisis où la balle atterrit, pas seulement où elle finit. La serviette te donne une cible d’atterrissage précise.',
    youtube_url: null,
    category: 'short_game',
    difficulty: 'beginner',
    duration_minutes: 15,
    attempts: 10,
    success_threshold: 6,
    success_rule: 'Réussir 6 chips sur 10 : balle atterrie sur la serviette posée à 5 m',
    steps: [
      'Pose une serviette pliée sur le green, à environ 5 m de ta balle.',
      'Mets-toi à l’adresse avec un wedge ou un fer 9, le poids sur le pied avant.',
      'Vise le centre de la serviette comme point d’atterrissage et joue un petit swing sans casser les poignets.',
      'Compte les balles qui touchent la serviette en premier et regarde comment elles roulent ensuite.',
    ],
    equipment: ['Wedge ou fer 9', '10 balles', 'Serviette'],
  },
  {
    id: '24',
    title: 'Pitch à 20 mètres',
    description: 'Un pitch de 20 m demande un swing de longueur constante. Un cercle de 3 m autour du drapeau mesure ta régularité.',
    youtube_url: null,
    category: 'short_game',
    difficulty: 'intermediate',
    duration_minutes: 20,
    attempts: 10,
    success_threshold: 5,
    success_rule: 'Réussir 5 pitchs sur 10 : balle arrêtée à moins de 3 m du drapeau, depuis 20 m',
    steps: [
      'Place-toi à 20 m d’un drapeau, sur une herbe courte.',
      'Prends un pitching ou un sand wedge et joue un demi-swing, les mains à hauteur de hanche à la montée.',
      'Garde le même tempo pour les 10 balles : ne change que ta cible, jamais ton rythme.',
      'Compte les balles arrêtées à moins de 3 m du drapeau.',
    ],
    equipment: ['Pitching ou sand wedge', '10 balles', 'Drapeau ou cible'],
  },
  {
    id: '25',
    title: 'Putter depuis la frange',
    description: 'Depuis la frange, le putter est souvent le choix le plus sûr. Ce drill t’apprend à gérer la vitesse sur une herbe plus haute.',
    youtube_url: null,
    category: 'short_game',
    difficulty: 'beginner',
    duration_minutes: 10,
    attempts: 10,
    success_threshold: 7,
    success_rule: 'Réussir 7 coups sur 10 : balle arrêtée à moins de 1 m du trou, depuis la frange',
    steps: [
      'Place ta balle dans la frange, à 1 m du green, avec le trou à environ 5 m.',
      'Joue au putter avec un coup un peu plus ferme qu’à l’habitude : l’herbe freine la balle.',
      'Garde le même mouvement pour toutes tes balles.',
      'Compte les balles arrêtées à moins de 1 m du trou.',
    ],
    equipment: ['Putter', '10 balles'],
  },
  {
    id: '26',
    title: 'Un chip, trois clubs',
    description: 'La même cible avec trois clubs différents : tu vois combien chaque club vole et roule, et tu choisis le plus régulier.',
    youtube_url: null,
    category: 'short_game',
    difficulty: 'intermediate',
    duration_minutes: 20,
    attempts: 9,
    success_threshold: 5,
    success_rule: 'Réussir 5 chips sur 9 : balle arrêtée à moins de 2 m du trou, avec 3 clubs différents',
    steps: [
      'Place-toi à 2 m du green, avec le drapeau à environ 10 m de ta balle.',
      'Joue 3 balles avec un fer 8, 3 avec un pitching wedge et 3 avec un sand wedge.',
      'Ajuste ton point d’atterrissage à chaque club : moins il a de loft, plus la balle roule.',
      'Compte les balles arrêtées à moins de 2 m et repère le club avec lequel tu es le plus régulier.',
    ],
    equipment: ['Fer 8', 'Pitching wedge', 'Sand wedge', '9 balles'],
  },
  {
    id: '27',
    title: 'Ligne de sable',
    description: 'Dans un bunker, on frappe le sable, pas la balle. Une ligne tracée derrière la balle te donne un repère précis.',
    youtube_url: null,
    category: 'short_game',
    difficulty: 'beginner',
    duration_minutes: 15,
    attempts: 10,
    success_threshold: 8,
    success_rule: 'Réussir 8 sorties de bunker sur 10 : balle sortie sur le green',
    steps: [
      'Trace une ligne dans le sable, puis pose la balle à 5 cm devant, côté cible.',
      'Ouvre légèrement la face du sand wedge et enfonce tes pieds dans le sable.',
      'Fais entrer le club sur la ligne et finis ton swing haut, sans arrêter le geste.',
      'Compte les balles sorties sur le green, puis ratisse le sable.',
    ],
    equipment: ['Sand wedge', '10 balles', 'Râteau'],
  },
  {
    id: '28',
    title: 'Neuf positions autour du green',
    description: 'Neuf positions différentes, un seul essai par position. Tu t’entraînes à sauver le par comme en round.',
    youtube_url: null,
    category: 'short_game',
    difficulty: 'advanced',
    duration_minutes: 30,
    attempts: 9,
    success_threshold: 4,
    success_rule: 'Réussir 4 up & downs sur 9 positions, avec une seule balle par position',
    steps: [
      'Repère 9 positions autour du green, avec des lies et des distances différents, de 3 à 25 m.',
      'Joue chaque position une seule fois, puis termine au putter.',
      'Compte un up & down quand la balle est rentrée en deux coups depuis ta position.',
      'Note ton score et la position qui te pose le plus de problèmes.',
    ],
    equipment: ['Wedges', 'Putter', '9 balles'],
  },
  {
    id: '7',
    title: '9 to 3 — contact propre',
    description: "Fais des swings courts (9h à 3h) avec un fer 7. Objectif: contact propre et trajectoire droite.",
    youtube_url: 'https://www.youtube.com/watch?v=27HWglP_x2o',
    category: 'approach',
    difficulty: 'beginner',
    duration_minutes: 15,
    attempts: 20,
    success_threshold: 14,
    success_rule: 'Réussir 14 balles sur 20 avec un contact net et une trajectoire droite',
    steps: [
      'Prends un fer 7, les pieds un peu moins écartés que pour un swing complet.',
      'Monte jusqu’à ce que tes bras soient parallèles au sol (9 h), puis finis de l’autre côté, bras parallèles (3 h).',
      'Garde la tête stable et touche la balle avant le sol.',
      'Compte les balles qui partent droit avec un contact net.',
    ],
    equipment: ['Fer 7', '20 balles'],
  },
  {
    id: '8',
    title: 'Fer contre mur',
    description: "Debout face à un mur (10cm), descends le club sans le toucher. Corrige les défauts de swing intérieur.",
    youtube_url: null,
    category: 'approach',
    difficulty: 'intermediate',
    duration_minutes: 10,
    attempts: 10,
    success_threshold: 8,
    success_rule: 'Réussir 8 swings sur 10 sans toucher le mur',
    steps: [
      'Mets-toi à l’adresse avec un fer 7, la tête du club à environ 10 cm du mur.',
      'Monte lentement le club sans toucher le mur.',
      'Redescends en gardant la même trajectoire, toujours sans toucher le mur.',
      'Compte les swings réussis sur 10 et recule un peu si tu touches trop souvent.',
    ],
    equipment: ['Fer 7', 'Un mur', 'Pas de balle'],
  },
  {
    id: '9',
    title: 'Approche 100m / 150m / 200m',
    description: "10 balles à chaque distance. Note les résultats. Identifie quelle distance te coûte le plus de coups.",
    youtube_url: null,
    category: 'approach',
    difficulty: 'intermediate',
    duration_minutes: 30,
    attempts: 30,
    success_threshold: 12,
    success_rule: 'Réussir 12 balles sur 30 à moins de 15 m de la cible, en notant chaque distance',
    steps: [
      'Repère trois cibles à 100, 150 et 200 m, et choisis le bon club pour chacune.',
      'Joue 10 balles sur la première cible avec la même routine à chaque balle.',
      'Note les balles arrivées à moins de 15 m, puis passe aux deux autres distances.',
      'Compare tes trois scores pour repérer la distance qui te coûte le plus de coups.',
    ],
    equipment: ['Fers et bois', '30 balles', 'Carnet ou téléphone'],
  },
  {
    id: '29',
    title: 'Wedges de 50 à 80 mètres',
    description: 'Trois distances de wedge et des cibles précises : tu apprends à contrôler la longueur de ton swing.',
    youtube_url: null,
    category: 'approach',
    difficulty: 'intermediate',
    duration_minutes: 15,
    attempts: 10,
    success_threshold: 5,
    success_rule: 'Réussir 5 balles sur 10 à moins de 10 m de la cible, entre 50 et 80 m',
    steps: [
      'Repère trois cibles à 50, 65 et 80 m sur le practice.',
      'Joue 3 balles vers 50 m, 3 vers 65 m, puis 4 vers 80 m, en changeant la longueur de swing.',
      'Fais un seul swing d’essai par balle, puis joue sans attendre.',
      'Compte les balles arrivées à moins de 10 m de la cible visée.',
    ],
    equipment: ['Pitching ou gap wedge', '10 balles', 'Cibles du practice'],
  },
  {
    id: '30',
    title: 'Cible du fer 7',
    description: 'Un seul club vers une seule cible : dix balles pour mesurer ta précision réelle sur une distance courante.',
    youtube_url: null,
    category: 'approach',
    difficulty: 'intermediate',
    duration_minutes: 15,
    attempts: 10,
    success_threshold: 6,
    success_rule: 'Réussir 6 balles sur 10 à moins de 15 m de la cible, au fer 7',
    steps: [
      'Choisis une cible à la portée de ton fer 7, entre 100 et 140 m.',
      'Répète la même routine avant chaque balle : cible, trajectoire, un swing d’essai.',
      'Joue 10 balles sans changer de club ni de cible.',
      'Compte les balles arrêtées à moins de 15 m de la cible.',
    ],
    equipment: ['Fer 7', '10 balles', 'Cible du practice'],
  },
  {
    id: '31',
    title: 'Serviette derrière la balle',
    description: 'Une serviette posée derrière la balle t’oblige à frapper la balle avant le sol. C’est le contact qui fait la distance.',
    youtube_url: null,
    category: 'approach',
    difficulty: 'beginner',
    duration_minutes: 15,
    attempts: 10,
    success_threshold: 8,
    success_rule: 'Réussir 8 frappes sur 10 : balle touchée avant le sol, sans toucher la serviette',
    steps: [
      'Pose une serviette roulée à 10 cm derrière la balle, sur la ligne de jeu.',
      'Prends un fer 7 et garde le centre de ton corps stable pendant le swing.',
      'Touche la balle d’abord, puis le sol devant elle : le club ne doit pas heurter la serviette.',
      'Compte les frappes nettes sur 10 ; si tu touches la serviette, ralentis ton swing.',
    ],
    equipment: ['Fer 7', '10 balles', 'Serviette roulée'],
  },
  {
    id: '32',
    title: 'Deux clubs au sol',
    description: 'Deux clubs posés au sol aident à aligner pieds et cible. Tu apprends à partir droit vers l’endroit visé.',
    youtube_url: null,
    category: 'approach',
    difficulty: 'beginner',
    duration_minutes: 20,
    attempts: 20,
    success_threshold: 12,
    success_rule: 'Réussir 12 balles sur 20 dans un couloir de 20 m de large, à environ 100 m',
    steps: [
      'Pose un premier club au sol vers ta cible et un second, parallèle, le long de la ligne de tes pieds.',
      'Vérifie que tes pieds, tes hanches et tes épaules sont parallèles aux clubs.',
      'Joue 20 balles au fer 8 vers une cible à environ 100 m.',
      'Compte les balles restées dans un couloir de 20 m de large autour de la cible.',
    ],
    equipment: ['Fer 8', '20 balles', '2 clubs ou baguettes d’alignement'],
  },
  {
    id: '33',
    title: 'Neuf cibles, neuf coups',
    description: 'Une cible et un club différents à chaque balle, une seule chance. Tu simules l’enchaînement des approches d’un parcours.',
    youtube_url: null,
    category: 'approach',
    difficulty: 'advanced',
    duration_minutes: 25,
    attempts: 9,
    success_threshold: 5,
    success_rule: 'Réussir 5 coups sur 9 à moins de 12 m de la cible annoncée',
    steps: [
      'Choisis 9 cibles du practice, de 80 à 160 m, et mélange leur ordre.',
      'Avant chaque balle, annonce la cible, le club et la trajectoire voulue.',
      'Joue chaque balle une seule fois, comme sur un parcours : pas de seconde chance.',
      'Compte les balles arrêtées à moins de 12 m de la cible annoncée.',
    ],
    equipment: ['Fers et wedges', '9 balles', 'Carnet ou téléphone'],
  },
  {
    id: '34',
    title: 'Matrice de wedge',
    description: 'Connaître tes distances de wedge évite de deviner sur le parcours. Tu mesures puis tu vérifies chaque longueur de swing.',
    youtube_url: null,
    category: 'approach',
    difficulty: 'intermediate',
    duration_minutes: 25,
    attempts: 9,
    success_threshold: 6,
    success_rule: 'Réussir 6 balles sur 9 à plus ou moins 5 m de la distance visée pour chaque longueur de swing',
    steps: [
      'Prends un wedge et choisis trois longueurs de swing : demi, trois quarts et plein.',
      'Calibre : joue 3 balles par longueur sans compter et note leur distance moyenne.',
      'Joue ensuite 3 balles par longueur en visant cette distance moyenne.',
      'Compte les balles de cette seconde série qui arrivent à plus ou moins 5 m de la distance visée.',
    ],
    equipment: ['Wedge', '18 balles', 'Carnet ou téléphone'],
  },
  {
    id: '10',
    title: 'Drive en douceur 80%',
    description: "Frappe 20 drives à 80% de puissance. Mesure la précision vs direction. La vitesse sans contrôle ne sert à rien.",
    youtube_url: null,
    category: 'driving',
    difficulty: 'beginner',
    duration_minutes: 20,
    attempts: 20,
    success_threshold: 12,
    success_rule: 'Réussir 12 drives sur 20 dans un couloir de 30 m de large',
    steps: [
      'Choisis une cible et repère un couloir de 30 m de large autour.',
      'Frappe tes drives à environ 80 % de ton effort, sans chercher la distance maximale.',
      'Garde le même tempo à chaque balle et finis ton swing en équilibre.',
      'Compte les balles restées dans le couloir.',
    ],
    equipment: ['Driver', '20 balles', '2 repères'],
  },
  {
    id: '11',
    title: 'Tempo 3:1',
    description: 'Monte en 3 temps, descends en 1. Utilise un métronome ou compte "un-deux-trois / frapper".',
    youtube_url: 'https://www.youtube.com/watch?v=5ojlon_LPDg',
    category: 'driving',
    difficulty: 'beginner',
    duration_minutes: 15,
    attempts: 10,
    success_threshold: 7,
    success_rule: 'Réussir 7 swings sur 10 avec une montée trois fois plus longue que la descente',
    steps: [
      'Commence par 3 swings sans balle en comptant « un-deux-trois » à la montée.',
      'Dis « frappe » pour la descente : elle ne dure qu’un temps, contre trois à la montée.',
      'Joue 10 balles avec ce rythme, sans accélérer en haut du swing.',
      'Compte les swings où le rythme est resté le même de bout en bout.',
    ],
    equipment: ['Driver ou fer', '10 balles', 'Métronome (facultatif)'],
  },
  {
    id: '12',
    title: 'Drive entre les cibles',
    description: "Choisis deux repères à 10m d'écart à 200m. Frappe 10 balles dans le couloir. Compte tes réussites.",
    youtube_url: null,
    category: 'driving',
    difficulty: 'intermediate',
    duration_minutes: 20,
    attempts: 10,
    success_threshold: 4,
    success_rule: 'Placer 4 drives sur 10 entre les deux repères écartés de 10 m',
    steps: [
      'Repère deux cibles écartées de 10 m, à environ 200 m de toi.',
      'Vise le milieu du couloir et prépare ta routine habituelle.',
      'Frappe 10 drives, un à la fois, sans te précipiter.',
      'Compte les balles passées entre les deux repères.',
    ],
    equipment: ['Driver', '10 balles', '2 repères'],
  },
  {
    id: '35',
    title: 'Fairway de 30 mètres',
    description: 'Un couloir de 30 m de large, comme un fairway de parcours. Dix drives, un seul objectif : rester dedans.',
    youtube_url: null,
    category: 'driving',
    difficulty: 'intermediate',
    duration_minutes: 20,
    attempts: 10,
    success_threshold: 6,
    success_rule: 'Réussir 6 drives sur 10 dans un couloir de 30 m de large, à environ 200 m',
    steps: [
      'Repère deux cibles écartées de 30 m, à environ 200 m, pour dessiner un fairway.',
      'Vise le milieu du couloir et choisis un point précis à l’adresse.',
      'Joue 10 drives avec ta routine habituelle, sans chercher la distance maximale.',
      'Compte les balles qui se posent dans le couloir et note de quel côté tu sors.',
    ],
    equipment: ['Driver', '10 balles', '2 repères'],
  },
  {
    id: '36',
    title: 'Départ sécurisé au bois 3',
    description: 'Sur un trou étroit, le bois 3 ou l’hybride garde la balle en jeu mieux qu’un driver. Ce drill te dit quel club choisir.',
    youtube_url: null,
    category: 'driving',
    difficulty: 'beginner',
    duration_minutes: 20,
    attempts: 10,
    success_threshold: 7,
    success_rule: 'Réussir 7 départs sur 10 dans un couloir de 30 m de large, à environ 180 m',
    steps: [
      'Repère deux cibles écartées de 30 m, à environ 180 m.',
      'Prends ton bois 3 ou ton hybride et place la balle sur un tee bas.',
      'Vise le milieu du couloir et swingue à environ 80 % de ta vitesse.',
      'Joue 10 balles, compte celles restées dans le couloir et compare avec ton driver.',
    ],
    equipment: ['Bois 3 ou hybride', '10 balles', 'Tees', '2 repères'],
  },
  {
    id: '37',
    title: 'Porte de départ à 5 mètres',
    description: 'La direction de départ de la balle dépend surtout de la face du club à l’impact. Une porte à 5 m te montre si elle est bien orientée.',
    youtube_url: null,
    category: 'driving',
    difficulty: 'intermediate',
    duration_minutes: 15,
    attempts: 10,
    success_threshold: 6,
    success_rule: 'Réussir 6 balles sur 10 passées dans une porte de 1 m de large, placée à 5 m',
    steps: [
      'Plante deux repères à 5 m devant ta balle, écartés de 1 m, sur ta ligne de jeu.',
      'Vérifie que personne ne se trouve devant toi ni dans la direction de la balle.',
      'Joue 10 balles au driver en visant le centre de la porte.',
      'Compte les balles qui passent dans la porte et note de quel côté tu manques.',
    ],
    equipment: ['Driver', '10 balles', 'Tees', '2 baguettes d’alignement'],
  },
  {
    id: '38',
    title: 'Quatorze départs',
    description: 'Quatorze départs, un par trou imaginaire. Tu enchaînes comme en round : un club à choisir, une seule balle, pas de seconde chance.',
    youtube_url: null,
    category: 'driving',
    difficulty: 'advanced',
    duration_minutes: 30,
    attempts: 14,
    success_threshold: 7,
    success_rule: 'Réussir 7 départs sur 14 dans un couloir de 30 m de large',
    steps: [
      'Repère un couloir de 30 m de large à environ 200 m.',
      'Pour chaque balle, imagine un trou différent et choisis ton club : driver ou bois 3.',
      'Joue chaque départ une seule fois avec ta routine complète.',
      'Compte les départs dans le couloir et vise 7 sur 14.',
    ],
    equipment: ['Driver', 'Bois 3', '14 balles', '2 repères'],
  },
  {
    id: '13',
    title: 'Routine de putting mental',
    description: "10 putts de 2m. Avant chaque putt: visualise la ligne, 2 pratiques, target focus. Zéro précipitation.",
    youtube_url: null,
    category: 'mental',
    difficulty: 'beginner',
    duration_minutes: 15,
    attempts: 10,
    success_threshold: 5,
    success_rule: 'Réussir 5 putts sur 10 depuis 2 m, avec ta routine complète à chaque putt',
    steps: [
      'Place 10 balles autour du trou, à 2 m.',
      'Avant chaque putt, visualise la balle qui roule de sa position jusqu’au trou.',
      'Fais deux swings d’essai en regardant le trou.',
      'Choisis un point cible précis, puis putte sans te précipiter.',
      'Compte les putts rentrés : la routine complète est obligatoire.',
    ],
    equipment: ['Putter', '10 balles'],
  },
  {
    id: '14',
    title: 'Simulation de trou',
    description: "Au practice, joue un trou imaginaire. Drive, approche, chip, putt. Tout avec la même routine qu'en compet.",
    youtube_url: null,
    category: 'mental',
    difficulty: 'advanced',
    duration_minutes: 30,
    attempts: 6,
    success_threshold: 3,
    success_rule: 'Réussir 3 trous sur 6 : quatre coups avec routine complète et putt rentré ou à moins de 30 cm',
    steps: [
      'Imagine un trou : un drive, une approche, un chip et un putt.',
      'Joue chaque coup avec ta routine de compétition, sur une cible précise.',
      'Enchaîne les quatre coups sans en rejouer aucun.',
      'Compte un trou réussi si le putt est rentré ou à moins de 30 cm.',
      'Joue six trous d’affilée et note ton score.',
    ],
    equipment: ['Driver', 'Fer', 'Wedge', 'Putter', 'Une vingtaine de balles'],
  },
  {
    id: '15',
    title: 'Respiration avant coup',
    description: "Sur 20 coups, impose-toi 3 respirations profondes avant chaque swing. Observe l'effet sur la précision.",
    youtube_url: null,
    category: 'mental',
    difficulty: 'beginner',
    duration_minutes: 20,
    attempts: 20,
    success_threshold: 12,
    success_rule: 'Réussir 12 coups sur 20 dans la cible, avec 3 respirations avant chaque swing',
    steps: [
      'Choisis un club et une cible de 20 m de large sur le practice.',
      'Avant chaque coup, prends 3 respirations lentes : inspire par le nez, souffle longuement par la bouche.',
      'Lance ton swing à la dernière expiration, sans te précipiter.',
      'Compte les balles dans la cible et compare avec tes séries habituelles.',
    ],
    equipment: ['Fer 7 ou club au choix', '20 balles'],
  },
  {
    id: '39',
    title: 'Visualisation de parcours',
    description: 'Sans club ni balle, tu joues un parcours dans ta tête avec une image nette de chaque coup. Idéal à la maison.',
    youtube_url: null,
    category: 'mental',
    difficulty: 'beginner',
    duration_minutes: 10,
    attempts: 9,
    success_threshold: 7,
    success_rule: 'Réussir 7 trous sur 9 : départ, approche et putt visualisés avec une cible précise',
    steps: [
      'Installe-toi au calme, assis, les yeux fermés, et choisis un parcours que tu connais bien.',
      'Pour chaque trou, visualise ton départ : la cible, la trajectoire et l’endroit où la balle atterrit.',
      'Enchaîne avec l’approche puis le putt, avec des images aussi nettes.',
      'Compte un trou réussi quand tu as vu les trois coups sans perdre l’image.',
    ],
    equipment: ['Carnet et stylo'],
  },
  {
    id: '40',
    title: 'Routine chronométrée',
    description: 'Une routine trop longue fait monter la tension, une routine trop courte laisse place au doute. Chronomètre la tienne.',
    youtube_url: null,
    category: 'mental',
    difficulty: 'intermediate',
    duration_minutes: 20,
    attempts: 10,
    success_threshold: 8,
    success_rule: 'Réussir 8 coups sur 10 avec une routine complète de 12 à 20 secondes',
    steps: [
      'Écris ta routine en quatre étapes : cible, image du coup, swing d’essai, départ.',
      'Lance le chrono au début de la routine et arrête-le au début du swing.',
      'Joue 10 balles au fer 7 en suivant tes quatre étapes dans l’ordre.',
      'Compte un succès à chaque routine complète terminée entre 12 et 20 secondes.',
    ],
    equipment: ['Fer 7', '10 balles', 'Chronomètre ou téléphone'],
  },
];

function getDaySeed(date: Date) {
  const startOfYear = new Date(date.getFullYear(), 0, 0);
  return Math.floor((date.getTime() - startOfYear.getTime()) / 86_400_000);
}

export function isDrillDoneToday(
  drillId: string,
  completions: DrillCompletion[],
  now = new Date()
) {
  return completions.some((completion) => (
    completion.drill_id === drillId && isSameDay(new Date(completion.completed_at), now)
  ));
}

export function getRecommendedDrills(categories: string[]) {
  const categorySet = new Set(categories);

  if (categorySet.size === 0) {
    return DRILLS;
  }

  return DRILLS.filter((drill) => categorySet.has(drill.category));
}

export function getDailyFocusDrill(input: {
  categories: string[];
  completions: DrillCompletion[];
  now?: Date;
}) {
  const now = input.now ?? new Date();
  const recommendedDrills = getRecommendedDrills(input.categories);
  const dueDrills = recommendedDrills.filter((drill) => !isDrillDoneToday(drill.id, input.completions, now));
  const pool = dueDrills.length > 0 ? dueDrills : recommendedDrills;

  if (pool.length === 0) {
    return null;
  }

  return pool[getDaySeed(now) % pool.length];
}
